name: flutter_chat_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_core: ^4.2.1 # Latest stable :contentReference[oaicite:0]{index=0}
  firebase_auth: ^6.1.2 # From FlutterFire BoM 4.3.0 :contentReference[oaicite:2]{index=2}
  firebase_storage: ^13.0.4 # Latest stable :contentReference[oaicite:3]{index=3}
  firebase_messaging: ^16.0.4 # (You can check if newer exists)
  firebase_analytics: ^12.0.2 # From FlutterFire BoM 4.3.0 :contentReference[oaicite:4]{index=4}
  cloud_firestore: ^6.1.0 # Latest Firestore :contentReference[oaicite:1]{index=1}

  # firebase_core: ^2.4.1
  # firebase_messaging: ^16.0.4
  # firebase_analytics: ^10.1.4
  # cloud_firestore: ^4.3.1
  # firebase_auth: ^4.2.5
  # firebase_storage: ^11.0.13

  image_picker: ^1.2.1
  provider: ^6.0.5
  path_provider: ^2.0.12
  file_picker: ^10.3.6
  flutter_launcher_icons: ^0.14.4
  badges: ^3.0.2

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/g2.png'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: MontThin
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf

    - family: MontReg
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: MontBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
